[workspace]
resolver = "2"
members = [
    "contracts/accessories/*",
    "contracts/main/*",
    "packages/polytone-evm",
    "scripts",
]
exclude = [
    "contracts/main/note",
    "contracts/main/proxy",
    "contracts/main/voice",
    "packages/cw-orch-polytone",
    "packages/polytone",
]

[workspace.package]
edition = "2021"
license = "BSD-3-Clause"
repository = "https://github.com/DA0-DA0/polytone"
rust-version = "1.67"
version = "3.0.0-rc"

[workspace.dependencies]
cw-orch-polytone = { package = "abstract-cw-orch-polytone", git = "https://github.com/permissionlessweb/polytone", branch = "zk-mvp" }
polytone = { package = "abstract-polytone", git = "https://github.com/permissionlessweb/polytone", branch = "zk-mvp" }
polytone-evm = { path = "packages/polytone-evm" }
polytone-note = { package = "abstract-polytone-note", git = "https://github.com/permissionlessweb/polytone", branch = "zk-mvp" }
polytone-proxy = { package = "abstract-polytone-proxy", git = "https://github.com/permissionlessweb/polytone", branch = "zk-mvp" }
polytone-voice = { package = "abstract-polytone-voice", git = "https://github.com/permissionlessweb/polytone", branch = "zk-mvp" }

cosmwasm-schema = { git = "https://github.com/permissionlessweb/cosmwasm", branch = "zk-mvp" }
cosmwasm-std = { git = "https://github.com/permissionlessweb/cosmwasm", branch = "zk-mvp" }
cw-storage-plus = { git = "https://github.com/permissionlessweb/cw-storage-plus", branch = "zk-mvp" }
cw-utils = { git = "https://github.com/permissionlessweb/cw-minus", branch = "zk-mvp" }
cw2 = { git = "https://github.com/permissionlessweb/cw-minus", branch = "zk-mvp" }

serde = { version = "1.0.145", default-features = false, features = ["derive"] }
sha2 = "0.10.6"
thiserror = "1.0.31"
# dev-dependencies

anyhow = { version = "1.0.51" }
cw-multi-test = { package = "abstract-cw-multi-test", git = "https://github.com/permissionlessweb/cw-multi-test-fork", branch = "zk-mvp" }
cw-orch = { git = "https://github.com/permissionlessweb/cw-orchestrator", branch = "zk-mvp" }
cw-orch-interchain = { git = "https://github.com/permissionlessweb/cw-orchestrator", branch = "zk-mvp" }

[profile.release]
codegen-units = 1
debug = false
debug-assertions = false
incremental = false
lto = true
opt-level = 3
overflow-checks = true   # very important, do not turn these off.
panic = 'abort'
rpath = false

[patch.crates-io]

nam-blst = { git = "https://github.com/permissionlessweb/blst", branch = "zk-mvp" }
