[workspace]
resolver = "2"
members = [
  "packages/polytone-evm",
  "contracts/accessories/*",
  "contracts/main/*",
  "scripts",
]
exclude = [
  "packages/polytone",
  "packages/cw-orch-polytone",
]

[workspace.package]
edition = "2021"
license = "BSD-3-Clause"
repository = "https://github.com/DA0-DA0/polytone"
rust-version = "1.67"
version = "3.0.0-rc"

[profile.release]
codegen-units = 1
debug = false
debug-assertions = false
incremental = false
lto = true
opt-level = 3
overflow-checks = true   # very important, do not turn these off.
panic = 'abort'
rpath = false

[workspace.dependencies]
polytone-evm = { path = "packages/polytone-evm" }
polytone = { package = "abstract-polytone", path = "../polytone/packages/polytone" }
polytone-proxy = { package = "abstract-polytone-proxy", path = "../polytone/contracts/main/proxy" }
polytone-note = { package = "abstract-polytone-note", path = "../polytone/contracts/main/note" }
polytone-voice = { package = "abstract-polytone-voice", path = "../polytone/contracts/main/voice" }
cw-orch-polytone = { package = "abstract-cw-orch-polytone", path = "../polytone/packages/cw-orch-polytone" }

cosmwasm-schema = { path = "../ZK/cw/zk-cosmwasm/packages/schema" }
cosmwasm-std = { path = "../ZK/cw/zk-cosmwasm/packages/std" }
cw-storage-plus = { path = "../ZK/cw/zk-storage-plus" }
cw-utils = { path = "../ZK/cw/zk-cw-minus/packages/cw-utils" }
cw2 = { path = "../ZK/cw/zk-cw-minus/packages/cw2" }

serde = { version = "1.0.145", default-features = false, features = ["derive"] }
thiserror = "1.0.31"
sha2 = "0.10.6"

# dev-dependencies

cw-orch = { path = "../cw-orchestrator/cw-orch" }
cw-orch-interchain = { path = "../cw-orchestrator/cw-orch-interchain" }
cw-multi-test = { path = "../cw-multi-test-fork" }
anyhow = { version = "1.0.51" }

[patch.crates-io]
nam-blst = { path = "../nam-blst/bindings/rust" }