[workspace]
members = [
    "contracts/accessories/*",
    "contracts/main/*",
    "packages/*",
    "scripts",
]

[workspace.package]
edition = "2021"
license = "BSD-3-Clause"
repository = "https://github.com/DA0-DA0/polytone"
rust-version = "1.67"
version = "3.0.0-rc"

[workspace.dependencies]
cw-orch-polytone = { path = "packages/cw-orch-polytone", package = "abstract-cw-orch-polytone" }
polytone = { path = "packages/polytone", package = "abstract-polytone" }
polytone-note = { path = "contracts/main/note", package = "abstract-polytone-note" }
polytone-proxy = { path = "contracts/main/proxy", package = "abstract-polytone-proxy" }
polytone-voice = { path = "contracts/main/voice", package = "abstract-polytone-voice" }

cosmwasm-schema = { path = "../cosmwasm/packages/schema" }
cosmwasm-std = { path = "../cosmwasm/packages/std" }
cw-storage-plus = { path = "../cw-storage-plus" }
cw-utils = { path = "../cw-minus/packages/cw-utils" }
cw2 = { path = "../cw-minus/packages/cw2" }

serde = { version = "1.0.145", default-features = false, features = ["derive"] }
# the sha2 version here is the same as the one used by
# cosmwasm-std. when bumping cosmwasm-std, this should also be
# updated. to find cosmwasm_std's sha function:
# ```cargo tree --package cosmwasm-std```
sha2 = "0.10.6"
thiserror = "1.0.31"

# dev-dependencies
cw-orch = { path = "../cw-orchestrator/cw-orch" }
cw-orch-interchain = { path = "../cw-orchestrator/cw-orch-interchain" }

anyhow = { version = "1.0.51" }
cw-multi-test = { package = "abstract-cw-multi-test", path = "../cw-multi-test-fork" }

[patch.'https://github.com/permissionlessweb/polytone']
abstract-cw-orch-polytone = { path = "packages/cw-orch-polytone" }
abstract-polytone = { path = "packages/polytone" }
abstract-polytone-note = { path = "contracts/main/note" }
abstract-polytone-proxy = { path = "contracts/main/proxy" }
abstract-polytone-voice = { path = "contracts/main/voice" }

[profile.release]
codegen-units = 1
debug = false
debug-assertions = false
incremental = false
lto = true
opt-level = 3
overflow-checks = true   # very important, do not turn these off.
panic = 'abort'
rpath = false
